### ISSUE TITLE
TypeError: string indices must be integers, not str

### ISSUE THREAD

**Issue by SamuelMarks** [nginxinc/crossplane#74] opened 2019-09-28 15:31 UTC
**Describe the bug**
I'm trying to write a simple parser emitter for nginx config—using crossplane—to create helper functions like `upsert_ssl_cert_to_443_block(conf_file, ssl_certificate, ssl_certificate_key)` and `upsert_block(conf_file, proxy_block, to_end_of_file=True)`.

But it looks like I can't include a specific config file—like [`tests/configs/includes-regular/foo.conf`](https://github.com/nginxinc/crossplane/blob/master/tests/configs/includes-regular/foo.conf)—but instead need a full file.

(I'm only interested in working with the simple config files that only have `server` and `upstream` blocks)

**To Reproduce**
Anyway, I thought I'd give your library a go, so plugged it into a standard Python test:
```python
from __future__ import absolute_import, print_function

from functools import partial
from os import path, remove
from tempfile import mkstemp
from unittest import TestCase, main as unittest_main
from string import Template

from crossplane import parse, build

configs_dir = partial(path.join,
                      path.join(path.dirname(path.dirname(__file__)), 'configs'))


class OTemplate(Template):
    delimiter = '_0_'
    idpattern = r'[a-z][_a-z0-9]*'


class TestParseEmit(TestCase):
    def setUp(self):
        self.nginx = configs_dir('nginx.conf')
        self.two_roots = configs_dir('two_roots.conf')
        self.temp_file = mkstemp()[1]  # Would prefer a `StringIO` instance

    def tearDown(self):
        remove(self.temp_file)

    def test_add_security(self):
        previous = ''
        with open(self.nginx, 'rt') as f0,
             open(self.two_roots, 'rt') as f1,
             open(self.temp_file, 'wt') as f2:
            previous = OTemplate(f0.read()).substitute(SERVER_BLOCK=f1.read())
            f2.write(previous)
        self.assertEqual(previous, build(parse(self.temp_file)))


if __name__ == '__main__':
    unittest_main()
```

`nginx.conf`
```
events {
    worker_connections 1024;
}

http {
    _0_SERVER_BLOCK
}
```

`two_roots.conf` [Would prefer to just use this file, and not have to embed it within `nginx.conf`)
```
server {
    # Other comment
    server_name github.com;
    listen 80;
    return 301 https://$server_name$request_uri;
}

server {
    # Random comment
    server_name github.com;
    listen 443 ssl;

    location /api0 {
        proxy_set_header Host $http_host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Scheme $scheme;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass http://127.0.0.1:5000/awesome;
        proxy_redirect off;
    }
}

````

**Expected behavior**
Test should pass, or give a small error about comments being missing (which should be solvable by passing `comments=True` argument).

**Your environment**
* Operating System: macOS 10.14.6 with Python 2.7.16 (with special attention to always have 3.3+ support)
* Version of crossplane: 0.5.3

**Additional context**
```
Error
Traceback (most recent call last):
  File "python@2/2.7.16_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/unittest/case.py", line 329, in run
    testMethod()
  File "/test/test_crossplane.py", line 45, in test_add_security
    self.assertEqual(previous, build(parse(temp_file)))
  File "lib/python2.7/site-packages/crossplane/builder.py", line 123, in build
    body = _build_block(body, payload, 0, 0)
  File "lib/python2.7/site-packages/crossplane/builder.py", line 89, in _build_block
    directive = _enquote(stmt['directive'])
TypeError: string indices must be integers, not str
```

**Comment by SamuelMarks** [comment] 2019-09-29 12:23
I have now implemented both functions, using a [pyparsing](https://github.com/pyparsing/pyparsing) [implementation of nginx parser](https://github.com/fatiherikli/nginxparser):
- [`upsert_redirect_to_443_block(conf_file, server_name)`](https://github.com/offscale/nginx-parse-emit/blob/98c01a4/nginx_parse_emit/emit.py#L102-L133)
- [`upsert_ssl_cert_to_443_block(conf_file, server_name,ssl_certificate, ssl_certificate_key)`](https://github.com/offscale/nginx-parse-emit/blob/98c01a4/nginx_parse_emit/emit.py#L136-L174)

**Comment by SamuelMarks** [comment] 2019-09-29 12:24
I have now implemented both functions, using a [pyparsing](https://github.com/pyparsing/pyparsing) [implementation of nginx parser](https://github.com/fatiherikli/nginxparser):
- [`upsert_redirect_to_443_block(conf_file, server_name)`](https://github.com/offscale/nginx-parse-emit/blob/98c01a4/nginx_parse_emit/emit.py#L102-L133)
- [`upsert_ssl_cert_to_443_block(conf_file, server_name, ssl_certificate, ssl_certificate_key)`](https://github.com/offscale/nginx-parse-emit/blob/98c01a4/nginx_parse_emit/emit.py#L136-L174)

**Comment by aluttik** [comment] 2019-09-29 19:23
Glad you've figured out a solution that works for you @SamuelMarks. However, if you still want to use crossplane, the problem is that you're trying to pass an entire configuration payload into `crossplane.build` instead of just one config file's contents.

Instead you'd need to do this:
```python
self.assertEqual(previous, build(parse(self.temp_file)['config'][0]['parsed']))
```
Or this:
```python
self.assertEqual(previous, crossplane.format(self.temp_file))
```

**Comment by aluttik** [comment] 2019-10-01 17:32
I'm going to close this issue because it's not a bug. If the solution doesn't work for you or you have any other questions, feel free to ask 🙂

**Closed** 2019-10-01 17:46 UTC

**Comment by SamuelMarks** [comment] 2020-02-25 13:23
@aluttik I started again, this time using crossplane and taking a different approach (this one is command-line driven). Expecting this to be a pretty useful little project.

How do I convert the output of `parse` back to a configuration file?

https://github.com/offscale/nginxctl/blob/3c0978a/nginxctl/tests/test_parser.py

I've tried what you have, and it isn't doing the trick. I either get:
```
TypeError: string indices must be integers
```

Or:
```
TypeError: expected str, bytes or os.PathLike object, not dict
```

Depending on what I pass it.  I've tried both `crossplane.format` and `crossplane.build`. I'm clearly missing something basic.

**Comment by linehammer** [comment] 2021-01-04 05:16
> TypeError: string indices must be integers, not str

TypeError:  means that you are trying to perform an operation on a value whose type is not compatible with that operation.  An Iterable is a collection of elements that can be accessed sequentially . In Python, iterable objects are indexed using numbers . When you try to access an iterable object using a string or a float as the index, an error will be returned as TypeError: [string indices must be integers](http://net-informations.com/python/err/indices.htm). This means that when you're accessing an iterable object like a string or float value, you must do it using an integer value.

**Comment by SamuelMarks** [comment] 2021-01-04 07:16
@linehammer Yes, I know what a `TypeError` is, as you can see I debugged the value and it showed unexpected value.

[my issue was mentioned in February 2020, it's January 2021…]
